name:                breaking-the-records
version:             0.1.0.0
github:              "desertsniper87/breaking-the-records"
license:             BSD3
author:              "Samidhya Sarker"
maintainer:          "torshobuet@gmail.com"
copyright:           "BSD2"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/desertsniper87/breaking-the-records#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  breaking-the-records-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - breaking-the-records

tests:
  breaking-the-records-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - breaking-the-records
